<?php /* @var $this MageProfis_RichSnippets_Block_Product */ ?>
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": <?php echo $this->jsonEncode($this->getProduct()->getName()) ?>,
  
  <?php if ($this->getProduct()->getImage() != 'no_selection' && $this->getProduct()->getImage()): ?>
  "image": "<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image') ?>",
  <?php endif; ?>
  
  "description": <?php echo $this->getShortDescription() ?>,
  "sku": "<?php echo $this->getProduct()->getSku() ?>",
  
  <?php if($this->getProduct()->getManufacturer()): ?>
  "brand": {
    "@type": "Thing",
    "name": <?php echo $this->jsonEncode($this->getProduct()->getAttributeText('manufacturer')) ?>
  },
  <?php endif; ?>
  
  <?php if($this->getRatingValue()): ?>
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "<?php echo $this->getRatingValue() ?>",
    "reviewCount": "<?php echo $this->getRatingCount() ?>"
  },
  <?php endif; ?>
  
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $this->getCurrencyCode() ?>",
    "price": "<?php echo $this->getFinalPriceInclTax() ?>",
    
    <?php if ($this->getProduct()->isSaleable()): ?>
    "availability": "http://schema.org/InStock"
    <?php else: ?>
    "availability": "http://schema.org/SoldOut"
    <?php endif; ?>
  }
}
</script>