<?php
/*
 * This should be build as php array and converted to json... @('_')@
 */
?>
<script type="application/ld+json">
    {
    	"@context": "http://schema.org",
    	"@type": "LocalBusiness",
        <?php if ($this->getDescription()): ?>
            "description": "<?php echo $this->getDescription() ?>",
        <?php endif; ?>
        <?php if ($this->getPricerange()): ?>
            "priceRange": "<?php echo $this->getPricerange() ?>",
        <?php endif; ?>
        <?php if ($this->getOpeninghoursn()): ?>
            "openingHours": <?php echo $this->getOpeninghoursn() ?>,
        <?php endif; ?>
        <?php if($this->getStoreName()): ?>
            "name": "<?php echo $this->getStoreName() ?>",
        <?php endif; ?>
        <?php if($this->getAddress('city') || $this->getAddress('region') || $this->getAddress('zip') || $this->getAddress('street')): ?>
    	"address": {
            "@type": "PostalAddress",
            <?php if ($this->getAddress('city')): ?>
                "addressLocality": "<?php echo $this->getAddress('city') ?>, Germany",
            <?php endif; ?>
            <?php if ($this->getAddress('region')): ?>
                "addressRegion": "<?php echo $this->getAddress('region') ?>",
            <?php endif; ?>
            <?php if ($this->getAddress('zip')): ?>
                "postalCode": "<?php echo $this->getAddress('zip') ?>",
            <?php endif; ?>
            <?php if ($this->getAddress('street')): ?>
                "streetAddress": "<?php echo $this->getAddress('street') ?>"
            <?php endif; ?>
    	},
        <?php endif; ?>
        <?php if($this->getEmail()): ?>
            "email": "<?php echo $this->getEmail() ?>",
        <?php endif; ?>
    	<?php if($this->getLogoUrl()): ?>
            "image": "<?php echo $this->getLogoUrl() ?>",
        <?php endif; ?>
    	"url": "<?php echo Mage::getBaseUrl() ?>",
        <?php if($this->getTelephone()): ?>
            "telephone": "<?php echo $this->getTelephone() ?>",
        <?php endif; ?>
    	"contactPoint": [{
    		"@type": "ContactPoint",
                <?php if($this->getTelephone()): ?>
                    "telephone": "<?php echo $this->getTelephone() ?>",
                <?php endif; ?>
    		"contactType": "customer service"
    	}]
    }
</script>