<?php /* @var $this MageProfis_RichSnippets_Block_Product */ ?>
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": <?php echo $this->jsonEncode($this->getProduct()->getName()) ?>,
  
  <?php if ($this->getProduct()->getImage() != 'no_selection' && $this->getProduct()->getImage()): ?>
  "image": "<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image') ?>",
  <?php endif; ?>
  
  "description": <?php echo $this->jsonEncode($this->getProduct()->getShortDescription()) ?>,
  "sku": "<?php echo $this->getProduct()->getSku() ?>",
  
  <?php if($this->getProduct()->getManufacturer()): ?>
  "brand": {
    "@type": "Thing",
    "name": <?php echo $this->jsonEncode($this->getProduct()->getAttributeText('manufacturer')) ?>
  },
  <?php endif; ?>
  
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $this->getCurrencyCode() ?>",
    "price": "<?php echo $this->getFinalPriceInclTax() ?>",
    
    <?php if ($_product->isSaleable()): ?>
    "availability": "http://schema.org/InStock"
    <?php else: ?>
    "availability": "http://schema.org/SoldOut"
    <?php endif; ?>
  }
}
</script>
<?php if($this->getBreadcrumbPath()): ?>
<?php
    $breadcrumb = array(
        '@context'        => 'http://schema.org',
        '@type'           => 'BreadcrumbList',
        'itemListElement' => array(),
    );
    $i = 0;
    foreach($this->getBreadcrumbPath() as $_item)
    {
        $i++;
        $breadcrumb['itemListElement'][] = array(
            '@type'    => 'ListItem',
            'position' => $i,
            'item' => array(
                '@id'  => $_item['link'],
                'name' => $_item['label'],
            )
        );
    }
?>
<script type="application/ld+json">
<?php echo $this->jsonEncode($breadcrumb) ?>
</script>
<?php endif; ?>